# Generated by Django 5.0.2 on 2024-08-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='country',
        ),
        migrations.RemoveField(
            model_name='property',
            name='country_code',
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='West Bengal', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(default='kolkata', max_length=255),
            preserve_default=False,
        ),
    ]
